services:
  dashboard_test:
    build:
      context: .
      dockerfile: Dockerfile
    image: archilitav/dashboard_test:latest
    container_name: dashboard_test
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3005:3005"  

